### ISSUE TITLE
No response after running the file

### ISSUE THREAD

**Issue by Rup-Royofficial** [emilgoldsmith/Codeforces-test-case-parser#1]
Whenever I try to run the file getTestCases.py along with the contest number from the url, it doesn't seem to work.

The file does run , but nothing more than that

**Comment by emilgoldsmith** [comment]
Hi @Rup-Royofficial, yes I haven't really been maintaining this repo, but I have a local copy I have maintained and used some months ago successfully so just copied that over and pushed it to this repo, give the new version a try and see if that works :).

Otherwise I'd suggest you try to debug it yourself, it's just a python script in the end, and I'm not really invested in spending a lot of time maintaining this repo

**Comment by Rup-Royofficial** [comment]
ok 👍
